media:
  input: assets/postimg
  output: /assets/postimg
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ cover, title ]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Post Date, type: date, required: true, options: { time: true, format: YYYY-MM-DD hh:mm:ss } }
      - { name: image, label: Cover image, type: image, required: true }
      - { name: optimized_image, label: (Select Same Image), type: image, required: true }
      - { name: subtitle, label: Subtitle, type: text, required: true }
      - { name: description, label: Description, type: text, required: true }
      - { name: category, label: Categories, type: select, options: { values: [ "news", "preview", "previous-event-pr" ] }, required: true }
      - { name: author, label: Author, type: string, required: true }
      - { name: tags, label: Tags, type: string, list: true, required: true }
      - { name: body, label: Body, type: rich-text, required: true }
  - name: config
    label: Jekyll config
    type: file
    path: _config.yml
    fields:
      - { name: title, label: Title, type: string, required: true }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: email, label: Email, type: string, pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" }
      - { name: description, label: Description, type: string }
      - { name: theme, label: Theme, type: string }
      - { name: plugins, label: Plugins, type: string, list: true }
      - { name: header_pages, label: Header pages, type: string, list: true }
      - name: minima
        label: Minima settings
        description: Minima specific settings, which are only available from Minima 3.0 onward.
        type: object
        fields:
          - { name: skin, label: Skin, type: select, options: { values: [ "classic", "dark", "auto", "solarized-light", "solarized-dark", "solarized" ] } }