media:
  input: assets/postimg
  output: /assets/postimg
content:
  - name: posts
    label: Posts
    path: bluebirdrivals.github.io/_posts
    type: collection
    fields:
      (...)
  - name: authors
    label: Authors
    path: _data/authors.json
    type: file
    fields:
      (...)